import test from 'node:test';import assert from 'node:assert/strict';import {fixture,PASSWORD} from './helpers.mjs';

test('成员变更、阶段闸门、利润结算和更正',async t=>{
 const f=await fixture(),{owner,all,action,base}=f;
 async function propose(kind,payload,reason='测试共同决策'){const p=await action(owner,'proposal.submit',{kind,payload,reason});return p.proposals.at(-1);}
 async function approve(g,clients=all){let p;for(const c of clients)p=await action(c,'proposal.vote',{id:g.id,decision:'approve',note:'共同确认'});return p;}
 await t.test('未验收前一阶段不能直接开放后一阶段',async()=>{const g=await propose('stage_open',{stageId:'stage-scale',evidence:'试图跳阶段'});await action(owner,'proposal.vote',{id:g.id,decision:'approve',note:''});await action(all[1],'proposal.vote',{id:g.id,decision:'approve',note:''});const r=await all[2].request(base+'/actions',{method:'POST',data:{type:'proposal.vote',data:{id:g.id,decision:'approve',note:''}}});assert.equal(r.status,400);assert.match(r.body.error,/前一阶段/);await action(owner,'proposal.cancel',{id:g.id,reason:'先完成前阶段'});});
 await t.test('阶段完成须全员验收，之后才能开放下一阶段',async()=>{await approve(await propose('stage_close',{stageId:'stage-pilot',evidence:'本阶段验证完成，无未验收任务或采购'}));const p=await approve(await propose('stage_open',{stageId:'stage-scale',evidence:'基于前阶段结果开放预算'}));assert.equal(p.stages[0].status,'completed');assert.equal(p.stages[1].status,'open');});
 await t.test('借款与出资不计入利润，待回款收入和销售成本分开确认',async()=>{let p=await action(owner,'ledger.add',{kind:'loan_in',amountCents:50000,description:'短期借款',evidence:'借款凭证'});await action(all[1],'ledger.verify',{id:p.ledger.at(-1).id,note:'核对借款'});p=await action(owner,'ledger.add',{kind:'receivable_revenue',amountCents:100001,description:'已经实现的销售收入尚未回款',evidence:'销售与交付证明'});await action(all[1],'ledger.verify',{id:p.ledger.at(-1).id,note:'核对收入'});p=await action(owner,'ledger.add',{kind:'cost_of_goods_sold',amountCents:40000,description:'对应销售成本',evidence:'成本结转依据'});p=await action(all[1],'ledger.verify',{id:p.ledger.at(-1).id,note:'核对成本'});assert.equal(p.finance.estimatedProfitCents,60001);assert.equal(p.finance.receivableCents,100001);});
 await t.test('结算会签期间账目变化，旧结算不能直接生效',async()=>{const g=await propose('settlement',{amountCents:10001,basis:'按已核实经营结果结算一部分'});await action(owner,'proposal.vote',{id:g.id,decision:'approve',note:''});await action(all[1],'proposal.vote',{id:g.id,decision:'approve',note:''});await action(owner,'ledger.add',{kind:'revenue',amountCents:100,description:'会签期间新收入',evidence:'收入凭证'});const r=await all[2].request(base+'/actions',{method:'POST',data:{type:'proposal.vote',data:{id:g.id,decision:'approve',note:''}}});assert.equal(r.status,409);assert.match(r.body.error,/账目已变化/);await action(owner,'proposal.cancel',{id:g.id,reason:'按新账目重新结算'});let p=await owner.ok(base,undefined,'GET');await action(all[1],'ledger.verify',{id:p.ledger.at(-1).id,note:'核实新收入'});});
 let settlement;
 await t.test('分配采用整数分且尾差守恒；全员确认后才可登记支付',async()=>{const p=await approve(await propose('settlement',{amountCents:10001,basis:'按当前已核实账目和约定比例结算'}));settlement=p.settlements.at(-1);assert.equal(settlement.allocations.reduce((s,a)=>s+a.amountCents,0),10001);assert.ok(settlement.allocations.every(a=>Number.isInteger(a.amountCents)));assert.equal(p.finance.settlementHolds,10001);});
 await t.test('分红付款不能超过批准给该成员的金额',async()=>{const a=settlement.allocations[0];const r=await owner.request(base+'/actions',{method:'POST',data:{type:'settlement.pay',data:{id:settlement.id,memberId:a.memberId,amountCents:a.amountCents+1,evidence:'不允许超额'}}});assert.equal(r.status,400);for(const a of settlement.allocations){let p=await action(owner,'settlement.pay',{id:settlement.id,memberId:a.memberId,amountCents:a.amountCents,evidence:'测试分红流水'});await action(all[1],'ledger.verify',{id:p.ledger.at(-1).id,note:'核对实际支付'});}const p=await owner.ok(base,undefined,'GET');assert.equal(p.finance.distributedCents,10001);assert.equal(p.settlements.at(-1).status,'paid');});
 await t.test('账目冲销追加记录，不删除原记录，且不能重复冲销',async()=>{let p=await action(owner,'ledger.add',{kind:'revenue',amountCents:500,description:'金额记录错误',evidence:'原始事实'});const original=p.ledger.at(-1);await action(all[1],'ledger.verify',{id:original.id,note:'已核对'});p=await action(owner,'ledger.reverse',{id:original.id,evidence:'发现错误，追加冲销'});const reversal=p.ledger.at(-1);assert.equal(reversal.amountCents,-500);assert.equal(reversal.reversesId,original.id);assert.ok(p.ledger.some(x=>x.id===original.id));await action(all[1],'ledger.verify',{id:reversal.id,note:'冲销依据核实'});const bad=await owner.request(base+'/actions',{method:'POST',data:{type:'ledger.reverse',data:{id:original.id,evidence:'重复'}}});assert.equal(bad.status,400);});
 await t.test('对账必须核对全部账目且余额一致',async()=>{let p=await owner.ok(base,undefined,'GET');const mismatch=await owner.request(base+'/actions',{method:'POST',data:{type:'proposal.submit',data:{kind:'reconcile',payload:{balanceCents:p.finance.verifiedCash+1,evidence:'不一致'},reason:'错误对账'}}});assert.equal(mismatch.status,400);p=await approve(await propose('reconcile',{balanceCents:p.finance.verifiedCash,evidence:'外部余额与登记一致'}));assert.ok(p.finance.lastReconciledAt);});
 let newcomer;
 await t.test('增加合伙人需要旧全体同意；已有未执行采购重新会签',async()=>{const q=await f.submitPurchase({stageId:'stage-scale'});let p=await approve(await propose('member_add',{name:'新合伙人',email:'newpartner@example.test',role:'partner'}));assert.equal(p.purchases.find(x=>x.id===q.id).status,'draft');const m=p.members.at(-1);assert.equal(m.userId,null);const inv=await owner.ok(base+'/invites',{memberId:m.id});newcomer=f.client();await newcomer.ok('/api/auth/accept',{token:inv.url.split('=')[1],name:'新合伙人',password:PASSWORD});await newcomer.reauth();await action(owner,'purchase.submit',{id:q.id});p=await owner.ok(base,undefined,'GET');assert.equal(p.purchases.find(x=>x.id===q.id).signers.length,4);await action(owner,'purchase.cancel',{id:q.id,reason:'成员变更测试结束'});});
 await t.test('移除成员必须包括本人在内的全体同意；最后一票可由退出者提交',async()=>{let p=await owner.ok(base,undefined,'GET'),m=p.members.at(-1),g=await propose('member_remove',{memberId:m.id},'该成员共同确认退出');for(const c of all)await action(c,'proposal.vote',{id:g.id,decision:'approve',note:'同意退出'});const result=await action(newcomer,'proposal.vote',{id:g.id,decision:'approve',note:'本人确认退出'});assert.equal(result.removedFromProject,true);assert.equal((await newcomer.request(base)).status,403);});
 await f.close();
});

// 达到容量上限时应拒绝新增，而不能新增后使所有后续会签陷入不可操作状态。
test('第31名合伙人在进入审批前即被拒绝，保留后续会签能力',async()=>{
 const {reduceProject}=await import('../src/domain.js');const f=await fixture();
 const p=await f.owner.ok(f.base,undefined,'GET');
 for(let i=p.members.length;i<30;i++)p.members.push({id:`limit-${i}`,userId:`limit-user-${i}`,email:`limit-${i}@example.test`,name:`成员${i}`,role:'partner',active:true,shareBps:0});
 assert.throws(()=>reduceProject(p,{type:'proposal.submit',data:{kind:'member_add',reason:'新增成员边界测试',payload:{name:'第三十一人',email:'limit31@example.test',role:'partner'}}},f.owner.user,{id:'test-limit',at:new Date().toISOString()}),/最多支持30/);
 await f.close();
});
