import test from 'node:test';import assert from 'node:assert/strict';import {fixture,PASSWORD} from './helpers.mjs';

test('访问控制、会话、附件与数据完整性',async t=>{
 const f=await fixture(),{owner,all,action,base,rt}=f;
 await t.test('匿名访问项目与附件被拒绝',async()=>{const anonymous=f.client();for(const path of [base,base+'/audit',base+'/export',base+'/files/no-such-id']){const r=await anonymous.request(path);assert.equal(r.status,401);}});
 await t.test('CSRF 和 Origin 校验不能由前端按钮绕过',async()=>{const data={type:'purchase.save',data:f.purchaseData()};const csrf=await owner.request(base+'/actions',{method:'POST',data,headers:{'x-csrf-token':'wrong'}});assert.equal(csrf.status,403);const cross=await owner.request(base+'/actions',{method:'POST',data,headers:{origin:'https://evil.example'}});assert.equal(cross.status,403);});
 await t.test('已初始化系统不能再次创建超级账号',async()=>{const r=await owner.request('/api/auth/bootstrap',{method:'POST',data:{token:'test-bootstrap-token-only',email:'evil@example.test',name:'恶意重置',password:PASSWORD}});assert.equal(r.status,409);});
 await t.test('重新登录不会继承旧会话的重要操作确认',async()=>{const c=f.client();await c.ok('/api/auth/login',{email:'owner@example.test',password:PASSWORD});const r=await c.request(base+'/actions',{method:'POST',data:{type:'project.pause',data:{reason:'缺少再次验证'}}});assert.equal(r.status,403);assert.equal(r.body.code,'REAUTH_REQUIRED');});
 await t.test('内部成员加入、附件归档接口不能伪造调用',async()=>{for(const type of ['member.join','attachment.add','channel.update','invite.create']){const r=await owner.request(base+'/actions',{method:'POST',data:{type,data:{}}});assert.equal(r.status,403);}});
 await t.test('金额必须是整数分，不能提交小数分和超限数据',async()=>{for(const value of [-1,1.5,100000000001]){const r=await owner.request(base+'/actions',{method:'POST',data:{type:'ledger.add',data:{kind:'contribution',amountCents:value,description:'无效金额',evidence:'测试'}}});assert.equal(r.status,400);}});
 await t.test('附件存入私有对象目录，下载强制附件且可核对实际 SHA-256',async()=>{const form=new FormData(),bytes=new TextEncoder().encode('purchase quote: testing');form.append('file',new Blob([bytes],{type:'text/plain'}),'../quote.txt');const file=await owner.request(base+'/files',{method:'POST',form});assert.equal(file.status,201);const {createHash}=await import('node:crypto');assert.equal(file.body.sha256,createHash('sha256').update(bytes).digest('hex'));assert.equal(file.body.name,'.._quote.txt');const get=await owner.request(base+'/files/'+file.body.id);assert.equal(get.status,200);assert.match(get.headers.get('content-disposition'),/^attachment/);assert.equal(get.body,'purchase quote: testing');});
 await t.test('HTML/SVG 文件不作为可执行附件接收',async()=>{const form=new FormData();form.append('file',new Blob(['<script>alert(1)</script>'],{type:'text/html'}),'attack.html');const r=await owner.request(base+'/files',{method:'POST',form});assert.equal(r.status,400);});
 let outsider;
 await t.test('另一个项目的成员不能查看本项目和凭证',async()=>{const other=await owner.ok('/api/projects',{name:'另一个隔离项目',totalBudgetCents:100000,minReserveCents:0});const p=await owner.ok(`/api/projects/${other.id}/actions`,{type:'member.add',data:{name:'无关项目成员',email:'outsider@example.test',role:'viewer'}});const inv=await owner.ok(`/api/projects/${other.id}/invites`,{memberId:p.members.at(-1).id});outsider=f.client();await outsider.ok('/api/auth/accept',{token:inv.url.split('=')[1],name:'无关成员',password:PASSWORD});for(const path of [base,base+'/export',base+'/audit',base+'/channels']){const r=await outsider.request(path);assert.equal(r.status,403);}const pp=await owner.ok(base,undefined,'GET');assert.equal((await outsider.request(base+'/files/'+pp.attachments[0].id)).status,403);});
 await t.test('伪造其他项目的附件 ID 不能关联',async()=>{const r=await owner.request(base+'/actions',{method:'POST',data:{type:'purchase.save',data:{...f.purchaseData(),attachments:['forged-other-project-file']}}});assert.equal(r.status,400);});
 await t.test('CSV 防公式注入，恶意标题只作为文本保存',async()=>{await action(owner,'ledger.add',{kind:'revenue',amountCents:100,description:'=HYPERLINK("https://evil.example")',evidence:'<script>window.attack=true</script>'});const r=await owner.request(base+'/ledger.csv');assert.equal(r.status,200);assert.match(r.body,/'=HYPERLINK/);const p=await owner.ok(base,undefined,'GET');assert.equal(p.ledger.at(-1).evidence,'<script>window.attack=true</script>');});
 await t.test('响应包含 CSP、HttpOnly 会话和禁止缓存的 API 头',async()=>{const r=await owner.request(base);assert.match(r.headers.get('content-security-policy'),/script-src 'self'/);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(r.headers.get('x-frame-options'),'DENY');const login=await owner.request('/api/auth/login',{method:'POST',data:{email:'owner@example.test',password:PASSWORD}});assert.match(login.headers.get('set-cookie'),/HttpOnly/);assert.match(login.headers.get('set-cookie'),/SameSite=Strict/);});
 await t.test('直接篡改项目状态会导致审计链校验失败',async()=>{const p=await owner.ok(base,undefined,'GET');const row=rt.db.prepare('SELECT state FROM projects WHERE id=?').get(f.pid),data=JSON.parse(row.state);data.name='篡改后的名称';rt.db.prepare('UPDATE projects SET state=? WHERE id=?').run(JSON.stringify(data),f.pid);const v=await owner.ok(base+'/audit/verify',undefined,'GET');assert.equal(v.valid,false);rt.db.prepare('UPDATE projects SET state=? WHERE id=?').run(row.state,f.pid);});
 await f.close();
});
