import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture, PASSWORD } from './helpers.mjs';

// 一个集成场景共享初始账号和项目，但每个子测试创建独立采购/决策或明确恢复状态。
test('多人合作：真实 API、数据库和授权流程',async t=>{
 const f=await fixture();const {owner,all,base,action,rt}=f;let q;
 await t.test('三名成员加入并共同确认基准后，项目进入执行阶段',async()=>{const p=await owner.ok(base,undefined,'GET');assert.equal(p.status,'active');assert.equal(p.members.filter(m=>m.userId).length,3);assert.equal(p.stages[0].status,'open');assert.equal(p.stages[1].status,'locked');assert.equal(p.finance.verifiedCash,1000000);});
 await t.test('知会和已阅不会自动构成批准',async()=>{q=await f.submitPurchase();await action(all[1],'purchase.read',{id:q.id,version:q.version});const p=await owner.ok(base,undefined,'GET');const actual=p.purchases.find(x=>x.id===q.id);assert.ok(actual.readBy[p.members[1].id]);assert.equal(Object.keys(actual.decisions).length,0);assert.equal(p.finance.holds,100000);});
 await t.test('一人批准不能下单，重复批准不能凑人数',async()=>{await action(owner,'purchase.vote',{id:q.id,version:q.version,decision:'approve',note:''});const duplicate=await owner.request(base+'/actions',{method:'POST',data:{type:'purchase.vote',data:{id:q.id,version:q.version,decision:'approve',note:''}}});assert.equal(duplicate.status,409);const order=await owner.request(base+'/actions',{method:'POST',data:{type:'purchase.order',data:{id:q.id,version:q.version,payee:q.payee,reference:'抢先下单'}}});assert.equal(order.status,409);});
 await t.test('补充要求会阻塞会签，回复评论本身也不是同意',async()=>{await action(all[1],'purchase.vote',{id:q.id,version:q.version,decision:'needs_info',note:'需要退货依据'});await action(owner,'purchase.comment',{id:q.id,text:'已补充可退货的依据'});let p=await owner.ok(base,undefined,'GET');assert.equal(p.purchases[0].status,'pending');await action(all[1],'purchase.vote',{id:q.id,version:q.version,decision:'approve',note:'依据已确认'});});
 await t.test('全员签齐才通过',async()=>{const p=await action(all[2],'purchase.vote',{id:q.id,version:q.version,decision:'approve',note:''});assert.equal(p.purchases[0].status,'approved');});
 await t.test('修改批准内容产生新版本，旧决定保留但全部失效',async()=>{let p=await action(owner,'purchase.save',{...f.purchaseData({title:'修订后采购',items:[{name:'样品',quantity:12,unitCents:10000}]}),id:q.id});q=p.purchases[0];assert.equal(q.version,2);assert.equal(q.status,'draft');assert.equal(q.history.length,1);assert.equal(Object.keys(q.decisions).length,0);assert.equal(p.finance.holds,0);await action(owner,'purchase.submit',{id:q.id});const stale=await all[1].request(base+'/actions',{method:'POST',data:{type:'purchase.vote',data:{id:q.id,version:1,decision:'approve',note:''}}});assert.equal(stale.status,409);});
 await t.test('一票反对不能通过，预算占用释放',async()=>{const p=await action(all[2],'purchase.vote',{id:q.id,version:q.version,decision:'reject',note:'目前没有必要扩大数量'});assert.equal(p.purchases[0].status,'rejected');assert.equal(p.finance.holds,0);await action(owner,'purchase.cancel',{id:q.id,reason:'本次不买'});});
 await t.test('尚未开放的下一阶段不可采购',async()=>{const next=await f.createPurchase({stageId:'stage-scale'});const r=await owner.request(base+'/actions',{method:'POST',data:{type:'purchase.submit',data:{id:next.id}}});assert.equal(r.status,409);assert.match(r.body.error,/阶段/);});
 await t.test('并发提交不会穿透阶段预算',async()=>{const a=await f.createPurchase({title:'并发A',items:[{name:'样品',quantity:35,unitCents:10000}]}),b=await f.createPurchase({title:'并发B',items:[{name:'样品',quantity:35,unitCents:10000}]});const results=await Promise.all([a,b].map(x=>owner.request(base+'/actions',{method:'POST',data:{type:'purchase.submit',data:{id:x.id}}})));assert.equal(results.filter(x=>x.status===200).length,1);assert.equal(results.filter(x=>x.status===409).length,1);const p=await owner.ok(base,undefined,'GET');assert.equal(p.finance.holds,350000);await action(owner,'purchase.cancel',{id:p.purchases.find(x=>x.status==='pending').id,reason:'并发测试结束，撤销未执行计划'});});
 await t.test('同供应商同阶段多笔采购给出拆单提示',async()=>{const a=await f.submitPurchase({title:'同供应商A'}),b=await f.submitPurchase({title:'同供应商B'});assert.match(b.splitWarning,/同阶段同供应商/);await action(owner,'purchase.cancel',{id:a.id,reason:'取消测试采购'});await action(owner,'purchase.cancel',{id:b.id,reason:'取消测试采购'});});
 await t.test('收款对象变更不能沿用批准',async()=>{q=await f.approvePurchase();const r=await owner.request(base+'/actions',{method:'POST',data:{type:'purchase.order',data:{id:q.id,version:q.version,payee:'另一个收款对象',reference:'wrong-payee'}}});assert.equal(r.status,409);await action(owner,'purchase.order',{id:q.id,version:q.version,payee:q.payee,reference:'ORD-001'});});
 await t.test('已下单不能改写原单',async()=>{const r=await owner.request(base+'/actions',{method:'POST',data:{type:'purchase.save',data:{...f.purchaseData(),id:q.id}}});assert.equal(r.status,409);});
 await t.test('相同幂等键重放付款只记录一次',async()=>{const key=crypto.randomUUID(),data={id:q.id,version:q.version,payee:q.payee,amountCents:50000,evidence:'真实付款模拟凭证'};const [a,b]=await Promise.all([owner.request(base+'/actions',{method:'POST',key,data:{type:'purchase.pay',data}}),owner.request(base+'/actions',{method:'POST',key,data:{type:'purchase.pay',data}})]);assert.equal(a.status,200);assert.equal(b.status,200);const p=await owner.ok(base,undefined,'GET');assert.equal(p.ledger.filter(x=>x.purchaseId===q.id&&x.kind==='purchase_payment').length,1);const conflict=await owner.request(base+'/actions',{method:'POST',key,data:{type:'purchase.pay',data:{...data,amountCents:10000}}});assert.equal(conflict.status,409);});
 await t.test('超额付款被后端拒绝',async()=>{const r=await owner.request(base+'/actions',{method:'POST',data:{type:'purchase.pay',data:{id:q.id,version:q.version,payee:q.payee,amountCents:60000,evidence:'不应该支付'}}});assert.equal(r.status,409);});
 await t.test('登记人不能复核自己的账目',async()=>{const p=await owner.ok(base,undefined,'GET'),entry=p.ledger.at(-1);const bad=await owner.request(base+'/actions',{method:'POST',data:{type:'ledger.verify',data:{id:entry.id,note:'自我复核'}}});assert.equal(bad.status,403);await action(all[1],'ledger.verify',{id:entry.id,note:'核对实际流水'});});
 await t.test('只有独立指定验收人可以登记收货，累计数量不能超购',async()=>{const r=await owner.request(base+'/actions',{method:'POST',data:{type:'purchase.receive',data:{id:q.id,quantities:[10],evidence:'错误验收人'}}});assert.equal(r.status,403);const over=await all[1].request(base+'/actions',{method:'POST',data:{type:'purchase.receive',data:{id:q.id,quantities:[11],evidence:'超量'}}});assert.equal(over.status,400);await action(all[1],'purchase.receive',{id:q.id,quantities:[4],evidence:'第一批4件合格'});const p=await action(all[1],'purchase.receive',{id:q.id,quantities:[6],evidence:'第二批6件合格'});assert.equal(p.purchases.find(x=>x.id===q.id).status,'received');});
 await t.test('未经批准但已发生的支出允许记录，并立即减少保守现金',async()=>{let p=await owner.ok(base,undefined,'GET'),cash=p.finance.conservativeCash;const next=await action(owner,'ledger.add',{kind:'operating_expense',amountCents:3000,description:'违规但实际花掉的钱',evidence:'真实支出说明',stageId:'stage-pilot'});assert.equal(next.ledger.at(-1).unauthorized,true);assert.equal(next.finance.conservativeCash,cash-3000);assert.equal(next.finance.unauthorized,3000);assert.ok(rt.db.prepare("SELECT COUNT(*) n FROM outbox WHERE channel='sms'").get().n>=3);await action(all[1],'ledger.verify',{id:next.ledger.at(-1).id,note:'确认发生，但不追认采购授权'});});
 await t.test('资金不确定的流入不能用于新采购',async()=>{const p=await owner.ok(base,undefined,'GET'),cash=p.finance.conservativeCash;const next=await action(owner,'ledger.add',{kind:'contribution',amountCents:10000,description:'尚未核实的资金',evidence:'待核对'});assert.equal(next.finance.conservativeCash,cash);assert.equal(next.finance.reportedCash,p.finance.reportedCash+10000);await action(all[1],'ledger.verify',{id:next.ledger.at(-1).id,note:'核对资金到账'});});
 await t.test('紧急暂停阻止新增承诺，但不会隐藏已有订单',async()=>{const pa=await action(all[2],'project.pause',{reason:'发现风险，暂停新增采购'});assert.equal(pa.status,'paused');const blocked=await owner.request(base+'/actions',{method:'POST',data:{type:'purchase.save',data:f.purchaseData()}});assert.equal(blocked.status,409);let p=await action(owner,'proposal.submit',{kind:'resume',payload:{},reason:'风险已处理，恢复正常流程'});const g=p.proposals.at(-1);for(const c of all)p=await action(c,'proposal.vote',{id:g.id,decision:'approve',note:''});assert.equal(p.status,'active');});
 await t.test('已生效项目不能由管理员直接修改计划/成员',async()=>{for(const type of ['plan.update','member.add','member.remove']){const r=await owner.request(base+'/actions',{method:'POST',data:{type,data:{email:'new@example.test',name:'未经批准的人'}}});assert.equal(r.status,400);}});
 await t.test('全员预算变更使未下单的采购失效重审，已执行订单历史保留',async()=>{const pending=await f.submitPurchase({title:'规则变更期间采购'});let p=await action(owner,'proposal.submit',{kind:'budget',payload:{totalBudgetCents:1200000,minReserveCents:100000,stageBudgets:{'stage-pilot':600000,'stage-scale':600000}},reason:'共同确认新的阶段预算'});const g=p.proposals.at(-1);for(const c of all)p=await action(c,'proposal.vote',{id:g.id,decision:'approve',note:''});const reset=p.purchases.find(x=>x.id===pending.id);assert.equal(reset.status,'draft');assert.equal(reset.version,2);assert.equal(p.purchases.find(x=>x.id===q.id).status,'received');assert.ok(reset.history.length);});
 await t.test('任务由指定负责人提交，指定的另一人验收',async()=>{let p=await owner.ok(base,undefined,'GET');p=await action(owner,'task.add',{title:'核对销售记录',stageId:'stage-pilot',dueDate:'2026-09-01',assigneeId:p.members[0].id,reviewerId:p.members[1].id,deliverable:'完整对账清单'});const t=p.tasks.at(-1);const bad=await all[2].request(base+'/actions',{method:'POST',data:{type:'task.progress',data:{id:t.id,status:'review',note:'冒充负责人'}}});assert.equal(bad.status,403);await action(owner,'task.progress',{id:t.id,status:'review',note:'已提交对账成果'});p=await action(all[1],'task.accept',{id:t.id,accept:true,note:'逐项核实，符合要求'});assert.equal(p.tasks.at(-1).status,'done');});
 await t.test('审计链校验通过，业务层没有审计删除能力',async()=>{const v=await owner.ok(base+'/audit/verify',undefined,'GET');assert.equal(v.valid,true);assert.ok(v.records>50);assert.throws(()=>rt.db.prepare('DELETE FROM audit WHERE project_id=?').run(f.pid),/audit_append_only/);const exported=await owner.ok(base+'/export',undefined,'GET');assert.equal(exported.auditVerification.valid,true);assert.equal(exported.audit.length,exported.revision);});
 await f.close();
});
