// 可选本地样例：仅允许 localhost，绝不在正式站点写入演示采购/财务。
import {readFile,writeFile,mkdir} from 'node:fs/promises';import {randomBytes} from 'node:crypto';import path from 'node:path';import {ROOT} from './local-runtime.mjs';
const origin=process.env.DEMO_URL||'http://localhost:8787';if(!['localhost','127.0.0.1'].includes(new URL(origin).hostname))throw Error('演示数据脚本只能用于 localhost');
const raw=await readFile(path.join(ROOT,'.dev.vars'),'utf8'),vars=Object.fromEntries(raw.split(/\r?\n/).filter(l=>l.includes('=')&&!l.startsWith('#')).map(l=>{const i=l.indexOf('=');return[l.slice(0,i),l.slice(i+1)];}));
const password='Demo-'+randomBytes(12).toString('base64url')+'!';
const day=n=>new Date(Date.now()+n*86400000).toISOString().slice(0,10);
const makeClient=()=>({cookie:'',csrf:'',async req(route,data){const r=await fetch(origin+route,{method:data?'POST':'GET',headers:{origin,'Content-Type':'application/json',cookie:this.cookie,'x-csrf-token':this.csrf,'x-idempotency-key':crypto.randomUUID()},body:data?JSON.stringify(data):undefined});const j=await r.json();if(!r.ok)throw Error(`${route}: ${r.status} ${j.error}`);if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(j.csrf)this.csrf=j.csrf;return j;}});
const owner=makeClient();const status=await owner.req('/api/auth/status');if(status.initialized)throw Error('本地数据库已经初始化。为防止污染已有数据，演示脚本拒绝重复执行。使用独立目录或自行登录创建项目。');
await owner.req('/api/auth/bootstrap',{token:vars.BOOTSTRAP_TOKEN,email:'owner@coop.local',name:'项目负责人',password});
let p=await owner.req('/api/projects',{name:'秋季商品试销合作',description:'先验证真实需求，再逐步采购。每次重要投入由三位合伙人共同确认。',totalBudgetCents:20000000,minReserveCents:3000000});const base='/api/projects/'+p.id,all=[owner],accounts=[{name:'项目负责人',email:'owner@coop.local',password}];
const act=(c,type,data)=>c.req(base+'/actions',{type,data});
for(const [name,email] of [['采购合伙人','purchase@coop.local'],['运营合伙人','operations@coop.local']]){p=await act(owner,'member.add',{name,email,role:'partner'});const m=p.members.at(-1),i=await owner.req(base+'/invites',{memberId:m.id}),c=makeClient();await c.req('/api/auth/accept',{token:i.url.split('=')[1],name,password});all.push(c);accounts.push({name,email,password});}
p=await owner.req(base);const ms=p.members;
p=await act(owner,'plan.update',{terms:'【合作边界】每笔采购由三位合伙人逐人同意，不把未回复视为同意。\n【资金安排】总预算20万元，始终保留3万元；未验收前阶段，不得直接扩大投入。\n【分工】采购合伙人负责供应商与报价；运营合伙人负责试销与客户反馈；项目负责人核对资金与整体计划。\n【分配与退出】分配按40% / 30% / 30%，依据共同确认的结算口径；成员退出及未结事项需共同确认。\n【异常】任何已发生支出都必须登记，不能因未批准而隐瞒。',shares:{[ms[0].id]:4000,[ms[1].id]:3000,[ms[2].id]:3000},stages:[{id:'pilot',name:'需求验证与小批量试销',budgetCents:6000000,goal:'验证客户需求、商品品质和真实交付成本',acceptance:'完成样品验收，提交试销反馈、毛利测算和退换货依据',endDate:day(14)},{id:'scale',name:'复盘后扩大采购',budgetCents:10000000,goal:'依据验证结果决定是否扩大采购，不提前占满资金',acceptance:'全体确认复盘结果、追加预算和库存退出预案',endDate:day(45)},{id:'close',name:'回款结算与复盘',budgetCents:4000000,goal:'核对回款、库存与应付，形成共同确认的结算',acceptance:'账目全部复核，未结事项说明完整，分配全员同意',endDate:day(70)}]});
for(const c of all)await c.req('/api/auth/reauth',{password});p=await act(owner,'proposal.submit',{kind:'baseline',payload:{},reason:'三位合伙人确认试销计划、阶段资金边界和合作职责'});const g=p.proposals.at(-1);for(const c of all)p=await act(c,'proposal.vote',{id:g.id,decision:'approve',note:'本人已阅读并明确同意'});
p=await act(owner,'ledger.add',{kind:'contribution',amountCents:20000000,description:'三位合伙人首期实缴出资（演示）',evidence:'演示账目，不代表真实资金。'});p=await act(all[1],'ledger.verify',{id:p.ledger.at(-1).id,note:'演示核对出资明细'});
const input={stageId:'pilot',category:'inventory',supplier:'晨光生活用品供应商（示例）',payee:'示例供应商 / 示例收款账户',paymentTerms:'订单确认后付部分款项，剩余货款验收后支付',reason:'小批量试销，验证实际客户需求，避免囤积大额库存。',risk:'关注交付延迟、售后退货及库存周转，单次采购控制在验证预算内。',exitPlan:'未拆封商品按协商条件退换；两周复盘，不达标停止追加。',quote:'已比较两家供应商的含运费报价，综合质量、交期与退货条件选择。',dueDate:day(7),expiresAt:day(5),executorId:ms[1].id,receiverId:ms[0].id};
p=await act(all[1],'purchase.save',{...input,title:'首批试销商品 · 120 件',items:[{name:'日用收纳套装',spec:'标准套装，含包装',quantity:120,unitCents:6800}]});let q=p.purchases.at(-1);await act(all[1],'purchase.submit',{id:q.id});for(const c of all)p=await act(c,'purchase.vote',{id:q.id,version:1,decision:'approve',note:'按试销数量执行'});await act(all[1],'purchase.order',{id:q.id,version:1,payee:q.payee,reference:'DEMO-ORDER-001（非真实订单）'});p=await act(owner,'purchase.pay',{id:q.id,version:1,payee:q.payee,amountCents:480000,evidence:'演示付款凭证，仅展示流程。'});await act(all[1],'ledger.verify',{id:p.ledger.at(-1).id,note:'示例流水核对'});await act(owner,'purchase.receive',{id:q.id,quantities:[120],evidence:'演示验收：数量与规格符合约定。'});
p=await act(all[1],'purchase.save',{...input,title:'第二批试销补货 · 100 件',items:[{name:'升级收纳组合',spec:'先试销，不追加超预算数量',quantity:100,unitCents:9600},{name:'整批配送费',spec:'固定费用',quantity:1,unitCents:50000}]});q=p.purchases.at(-1);await act(all[1],'purchase.submit',{id:q.id});await act(all[1],'purchase.vote',{id:q.id,version:1,decision:'approve',note:'报价与退货条件已核实'});await act(all[2],'purchase.vote',{id:q.id,version:1,decision:'approve',note:'试销反馈支持本次补货'});await act(all[2],'purchase.comment',{id:q.id,text:'建议先观察两周销售，库存未明显下降前不再追加采购。'});
for(const entry of [{kind:'revenue',amountCents:680000,description:'首轮试销已回款（演示）'},{kind:'cost_of_goods_sold',amountCents:320000,description:'对应试销商品销售成本（演示）'}]){p=await act(owner,'ledger.add',{...entry,evidence:'本地演示数据，非实际交易。'});await act(all[1],'ledger.verify',{id:p.ledger.at(-1).id,note:'示例核对'});}
for(const t of [{title:'整理本轮报价与退换货条款',assigneeId:ms[1].id,reviewerId:ms[0].id,deliverable:'两家报价对比、退款期限与配送条件',dueDate:day(1),status:'review',c:all[1],note:'已整理报价对比与退货条款，等待负责人验收。'},{title:'完成首轮试销客户回访',assigneeId:ms[2].id,reviewerId:ms[0].id,deliverable:'回访记录、主要问题与追加采购建议',dueDate:day(3),status:'doing',c:all[2],note:'已完成一半客户回访，正在汇总购买意愿。'},{title:'核对阶段资金与未结采购款',assigneeId:ms[0].id,reviewerId:ms[1].id,deliverable:'现金余额、未付货款和下一轮可安排资金',dueDate:day(2),status:'doing',c:owner,note:'已登记现有款项，等待银行流水逐项对齐。'}]){p=await act(owner,'task.add',{title:t.title,stageId:'pilot',assigneeId:t.assigneeId,reviewerId:t.reviewerId,deliverable:t.deliverable,dueDate:t.dueDate});await act(t.c,'task.progress',{id:p.tasks.at(-1).id,status:t.status,note:t.note});}
await mkdir(path.join(ROOT,'.local'),{recursive:true});await writeFile(path.join(ROOT,'.local/demo-accounts.json'),JSON.stringify({origin,projectId:p.id,accounts},null,2),{mode:0o600});console.log('本地演示数据已创建。账号和随机密码仅保存在 .local/demo-accounts.json；不要发布该文件。');
